//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearch.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocSearch.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   execMachineLearning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ARGKEY_EXEC_MACHINE_LEARNING {
            get {
                return ResourceManager.GetString("ARGKEY_EXEC_MACHINE_LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DEFAULT_PAGE_NO {
            get {
                return ResourceManager.GetString("DEFAULT_PAGE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXECUTE {
            get {
                return ResourceManager.GetString("EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crawl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HISTORY_KIND_CRAWL {
            get {
                return ResourceManager.GetString("HISTORY_KIND_CRAWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   word2vec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HISTORY_KIND_WORD2VEC {
            get {
                return ResourceManager.GetString("HISTORY_KIND_WORD2VEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   docContent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_DOC_CONTENT {
            get {
                return ResourceManager.GetString("JSON_RES_DOC_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   extention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_EXTENTION {
            get {
                return ResourceManager.GetString("JSON_RES_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fileFullPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_FILE_FULL_PATH {
            get {
                return ResourceManager.GetString("JSON_RES_FILE_FULL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fileName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_FILENAME {
            get {
                return ResourceManager.GetString("JSON_RES_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   folderPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_FOLDER_PATH {
            get {
                return ResourceManager.GetString("JSON_RES_FOLDER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _score に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_SCORE {
            get {
                return ResourceManager.GetString("JSON_RES_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   updatedDate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JSON_RES_UPDATED_DATE {
            get {
                return ResourceManager.GetString("JSON_RES_UPDATED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_SCORE {
            get {
                return ResourceManager.GetString("NO_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOT_EXECUTE {
            get {
                return ResourceManager.GetString("NOT_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CancelCrawl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_CANCEL_CRAWL {
            get {
                return ResourceManager.GetString("PROCESS_CANCEL_CRAWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CancelMachineLearning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_CANCEL_MACHINE_LEARNING {
            get {
                return ResourceManager.GetString("PROCESS_CANCEL_MACHINE_LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetHistoryData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_GET_HISTORY_DATA {
            get {
                return ResourceManager.GetString("PROCESS_GET_HISTORY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsCrawlExecuted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_IS_CRAWL_EXECUTED {
            get {
                return ResourceManager.GetString("PROCESS_IS_CRAWL_EXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsWord2VecLearned に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_IS_WORD2VEC_LEARNED {
            get {
                return ResourceManager.GetString("PROCESS_IS_WORD2VEC_LEARNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveScheduling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_SAVE_SCHEDULING {
            get {
                return ResourceManager.GetString("PROCESS_SAVE_SCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SetupCrawlFolders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_SETUP_CRAWL_FOLDER {
            get {
                return ResourceManager.GetString("PROCESS_SETUP_CRAWL_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartCrawl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_START_CRAWL {
            get {
                return ResourceManager.GetString("PROCESS_START_CRAWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartMachineLearning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROCESS_START_MACHINE_LEARNING {
            get {
                return ResourceManager.GetString("PROCESS_START_MACHINE_LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROGRESS_RATE_CANCELED {
            get {
                return ResourceManager.GetString("PROGRESS_RATE_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   101 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROGRESS_RATE_COMPLETED {
            get {
                return ResourceManager.GetString("PROGRESS_RATE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_DAILY {
            get {
                return ResourceManager.GetString("SCHEDULE_DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   detail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_DETAIL {
            get {
                return ResourceManager.GetString("SCHEDULE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_NONE {
            get {
                return ResourceManager.GetString("SCHEDULE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   oneTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_ONETIME {
            get {
                return ResourceManager.GetString("SCHEDULE_ONETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_WEEKLY {
            get {
                return ResourceManager.GetString("SCHEDULE_WEEKLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   searchFolder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SESSION_SEARCH_FOLDER {
            get {
                return ResourceManager.GetString("SESSION_SEARCH_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ........ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNIP {
            get {
                return ResourceManager.GetString("SNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HISTORY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TYPE_HISTORY {
            get {
                return ResourceManager.GetString("TYPE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROGRESS_BAR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TYPE_PROGRESS_BAR {
            get {
                return ResourceManager.GetString("TYPE_PROGRESS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SCHEDULING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TYPE_SCHEDULING {
            get {
                return ResourceManager.GetString("TYPE_SCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETUP_CRAWL_FOLDER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TYPE_SETUP_CRAWL_FOLDER {
            get {
                return ResourceManager.GetString("TYPE_SETUP_CRAWL_FOLDER", resourceCulture);
            }
        }
    }
}
