//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSearch.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocSearch.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BUTTON_FOLDER_CLEAR {
            get {
                return ResourceManager.GetString("BUTTON_FOLDER_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BUTTON_FOLDER_SELECT {
            get {
                return ResourceManager.GetString("BUTTON_FOLDER_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BUTTON_SEARCH {
            get {
                return ResourceManager.GetString("BUTTON_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLON {
            get {
                return ResourceManager.GetString("COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール処理がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWL_CANCELED {
            get {
                return ResourceManager.GetString("CRAWL_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロールファイル数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWL_FILE_NUM {
            get {
                return ResourceManager.GetString("CRAWL_FILE_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロールが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWL_FINISHED {
            get {
                return ResourceManager.GetString("CRAWL_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール先のフォルダを指定して下さい。改行で複数のフォルダを指定出来ます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWL_FOLDER_NOTE {
            get {
                return ResourceManager.GetString("CRAWL_FOLDER_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール先のフォルダの指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWL_FOLDER_SETUP {
            get {
                return ResourceManager.GetString("CRAWL_FOLDER_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール処理の開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWL_START {
            get {
                return ResourceManager.GetString("CRAWL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRAWLING {
            get {
                return ResourceManager.GetString("CRAWLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細設定の文字列が正しいcron形式になっていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRON_STRING_ERROR {
            get {
                return ResourceManager.GetString("CRON_STRING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DATETIME {
            get {
                return ResourceManager.GetString("DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXECUTE {
            get {
                return ResourceManager.GetString("EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FRIDAY {
            get {
                return ResourceManager.GetString("FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HISTORY_CRAWL {
            get {
                return ResourceManager.GetString("HISTORY_CRAWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械学習履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HISTORY_WORD2VEC {
            get {
                return ResourceManager.GetString("HISTORY_WORD2VEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件ヒット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HIT_COUNT {
            get {
                return ResourceManager.GetString("HIT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   挿入ファイル数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INSERT_FILE_NUM {
            get {
                return ResourceManager.GetString("INSERT_FILE_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械学習実行中です... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LEARNING {
            get {
                return ResourceManager.GetString("LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械学習処理がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LEARNING_CANCELED {
            get {
                return ResourceManager.GetString("LEARNING_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械学習が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LEARNING_FINISHED {
            get {
                return ResourceManager.GetString("LEARNING_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロール後の関連語学習 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MACHINE_LEARNING_AFTER_CRAWLING {
            get {
                return ResourceManager.GetString("MACHINE_LEARNING_AFTER_CRAWLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関連語学習の開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MACHINE_LEARNING_WORD2VEC {
            get {
                return ResourceManager.GetString("MACHINE_LEARNING_WORD2VEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関連語を表示する人工知能の学習の実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MACHINE_LEARNING_WORD2VEC_EXPLAIN {
            get {
                return ResourceManager.GetString("MACHINE_LEARNING_WORD2VEC_EXPLAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MONDAY {
            get {
                return ResourceManager.GetString("MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スケジュールが一度も実行されない設定です（過去日など）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_EXECUTE_DATE {
            get {
                return ResourceManager.GetString("NO_EXECUTE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロールが実行されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOT_CRAWLED {
            get {
                return ResourceManager.GetString("NOT_CRAWLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOT_EXECUTE {
            get {
                return ResourceManager.GetString("NOT_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械学習が実行されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOT_LEARNED {
            get {
                return ResourceManager.GetString("NOT_LEARNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PLACEHOLDER_KEYWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理開始の準備中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PREPAREING {
            get {
                return ResourceManager.GetString("PREPAREING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関連語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RELATED_WORD {
            get {
                return ResourceManager.GetString("RELATED_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string REVERT {
            get {
                return ResourceManager.GetString("REVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   土 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SATURDAY {
            get {
                return ResourceManager.GetString("SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SAVED {
            get {
                return ResourceManager.GetString("SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   crontab形式で指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_DETAIL_SETUP_EXPLAIN {
            get {
                return ResourceManager.GetString("SCHEDULE_DETAIL_SETUP_EXPLAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日毎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_EXEC_DAILY {
            get {
                return ResourceManager.GetString("SCHEDULE_EXEC_DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_EXEC_DETAIL {
            get {
                return ResourceManager.GetString("SCHEDULE_EXEC_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_EXEC_NOTHING {
            get {
                return ResourceManager.GetString("SCHEDULE_EXEC_NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1回のみ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_EXEC_ONE_TIME {
            get {
                return ResourceManager.GetString("SCHEDULE_EXEC_ONE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_EXEC_TIME {
            get {
                return ResourceManager.GetString("SCHEDULE_EXEC_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULE_EXEC_WEEKLY {
            get {
                return ResourceManager.GetString("SCHEDULE_EXEC_WEEKLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スケジュール設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SCHEDULING_SETUP {
            get {
                return ResourceManager.GetString("SCHEDULING_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SEARCH_FOLDER_LABEL {
            get {
                return ResourceManager.GetString("SEARCH_FOLDER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   類似文書検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SEARCH_SAME_KIND_DOC {
            get {
                return ResourceManager.GetString("SEARCH_SAME_KIND_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETUP_PAGE {
            get {
                return ResourceManager.GetString("SETUP_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   類似スコア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SIMILARITY_SCORE {
            get {
                return ResourceManager.GetString("SIMILARITY_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUNDAY {
            get {
                return ResourceManager.GetString("SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string THURSDAY {
            get {
                return ResourceManager.GetString("THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定画面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_SETUP {
            get {
                return ResourceManager.GetString("TITLE_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLBAR_TITLE_SEARCH {
            get {
                return ResourceManager.GetString("TOOLBAR_TITLE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLBAR_TITLE_SETUP {
            get {
                return ResourceManager.GetString("TOOLBAR_TITLE_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TUESDAY {
            get {
                return ResourceManager.GetString("TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UPDATE_DATE {
            get {
                return ResourceManager.GetString("UPDATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WEDNESDAY {
            get {
                return ResourceManager.GetString("WEDNESDAY", resourceCulture);
            }
        }
    }
}
